[features]
seeds = true
skip-lint = false
[programs.localnet]
first_anchor_program = "GqcREMZ4UrdS6VwgVf3gnMV3iKYGbSoDVEuURjpgmvSG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./tests/Usrw6vhCpH4uWYJ6WeTKUAGM1zzSREVzFPNdirtANDz.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
